# Generated by Django 4.1.3 on 2022-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat Room'},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='channel_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
